version: '3.1'

services:

  crawler:
    build: ./
    container_name: crawler
    command: 
      - aitah
      - "20"
    volumes:
      - ./docs/api:/app/docs/api
      - ./databases:/app/databases
